# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59d73bc33b855f3e41c98a91d10414428b869240fa63e46588cb5fc552dddcbd415ae0d994fa247d9475077128127c64cd090646f2668453df53b2aecce0293a

test:
  secret_key_base: 6c8d57daac0ef852631142de58061916cc87a0cb02fae24e440eac29d90b599cff9d1f838bb1ca50c1011ee56dd75d069c31486b68d7a11479774ac32e01cae6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
